USER 101 instead of postgres, for pod security policy verification
To avoid:
Error: container has runAsNonRoot and image has non-numeric user (postgres), cannot verify user is non-root